properties:
  configuration:
    ingress:
      external: true
      targetPort: 80
  template:
    containers:
      - image: __containerRegistryUrl__/__containerRepository__:__Build.BuildId__
        name: __containerAppName__
        probes:
          - type: Liveness
            httpGet:
              path: "/healthz"
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          - type: Readiness
            httpGet:
              path: "/healthz"
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
