trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 2024-02-aks-with-terraform/03-cluster

extends:
  template: ../templates/terraform.pipeline.yml
  parameters:
    serviceConnection: AzureSubscription
    buildAgent: windows-private
    terraformDir: $(System.DefaultWorkingDirectory)/2024-02-aks-with-terraform/03-cluster
