trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 2024-02-aks-with-terraform/01-network

extends:
  template: ../templates/terraform.pipeline.yml
  parameters:
    serviceConnection: AzureSubscription
    pool:
      vmImage: ubuntu-latest
    terraformDir: $(System.DefaultWorkingDirectory)/2024-02-aks-with-terraform/01-network
