parameters:
  - name: artifactName
    default: terraform
  - name: target
    default: $(build.artifactstagingdirectory)
  - name: publishedArtifactsDirectory
    default: "$(Pipeline.Workspace)/$(artifactName)"
  - name: planName
    default: tfplan
  - name: serviceConnection
  - name: pool
    type: object
  - name: terraformDir

stages:
  - stage: Plan
    pool: ${{ parameters.pool }}
    jobs:
      - job: Plan
        steps:
          - task: TerraformCLI@1
            displayName: terraform init
            inputs:
              command: "init"
              backendType: "azurerm"
              workingDirectory: ${{ parameters.terraformDir }}
              backendServiceArm: ${{ parameters.serviceConnection }}

          - task: TerraformCLI@1
            displayName: terraform validate
            inputs:
              command: "validate"
              backendType: "azurerm"
              workingDirectory: ${{ parameters.terraformDir }}
              environmentServiceName: ${{ parameters.serviceConnection }}

          - task: TerraformCLI@1
            displayName: terraform plan
            inputs:
              command: "plan"
              backendType: "azurerm"
              workingDirectory: ${{ parameters.terraformDir }}
              commandOptions: "-destroy -input=false -out=${{ parameters.planName }}"
              environmentServiceName: ${{ parameters.serviceConnection }}
              publishPlanResults: "Terraform plan"

          - task: CopyFiles@2
            displayName: Copy files
            inputs:
              SourceFolder: ${{ parameters.terraformDir }}
              Contents: |
                .terraform.lock.hcl
                **/*.tf
                **/*.tfvars
                **/*tfplan*
              TargetFolder: ${{ parametes.target }}

          - publish: ${{ parametes.target }}
            artifact: ${{ parameters.artifactName }}

  - stage: Destroy
    displayName: Destroy
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - deployment: Destroy
        environment: Azure
        pool: ${{ parameters.pool }}
        strategy:
          runOnce:
            deploy:
              steps:
                - download: "current"
                  artifact: ${{ parameters.artifactName }}

                - task: TerraformCLI@1
                  displayName: terraform init
                  inputs:
                    command: "init"
                    backendType: "azurerm"
                    workingDirectory: ${{ parameters.publishedArtifactsDirectory }}
                    backendServiceArm: ${{ parameters.serviceConnection }}

                - task: TerraformCLI@1
                  displayName: terraform destroy
                  inputs:
                    command: "apply"
                    commandOptions: '-destroy -input=false "${{ parameters.planName }}"'
                    backendType: "azurerm"
                    workingDirectory: ${{ parameters.publishedArtifactsDirectory }}
                    environmentServiceName: ${{ parameters.serviceConnection }}
