trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 2024-02-aks-with-terraform/02-utils

extends:
  template: ../templates/terraform.pipeline.yml
  parameters:
    serviceConnection: AzureSubscription
    buildAgent: ubuntu-latest
    terraformDir: $(System.DefaultWorkingDirectory)/2024-02-aks-with-terraform/02-utils
